version: '3'

services:
  node-app:
    image: "taarik/simple-node-app"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"
      restart_policy:
        condition: any
    command: npm run dev
    ports:
      - "9100:9100"

  flask-app:
    image: "taarik/my-simple-webapp"    
    ports:
      - "9101:5000"

  flask-app-another:
    image: "taarik/simple-py-app"
    ports:
      - "9102:5000"

  redis:
    image: "redis:alpine"
